<?php
return [
    'INDICES_DESCRIPTION' => 'XS Group adalah penyedia layanan finansial dan fintech global dengan entitas yang diatur dan diotorisasi oleh lembaga pengatur terkemuka di yurisdiksi keuangan paling terkemuka di seluruh dunia. Kami memberikan prioritas pada kepatuhan regulasi untuk memastikan kepercayaan, integritas, dan akuntabilitas dalam industri keuangan global. Operasi kami mematuhi regulasi dan persyaratan yang ditetapkan oleh otoritas yang berwenang di setiap yurisdiksi tempat kami beroperasi.',
    'TRADE_WORKDS_LEADING' => 'PERDAGANGAN INDEKS SAHAM TERKEMUKA DUNIA DENGAN BROKER GLOBAL',
    'DESCRIPTION_1' => 'Lepaskan Potensi Perdagangan indeks saham terkemuka dunia dan Perdagangan Indeks Saham Internasional dengan XS. Dapatkan Akses ke Pasar Global dan Bertransaksi Saham Indeks Terkemuka seperti Dow Jones, DAX, Nasdaq, dan lainnya. Bergabunglah dengan XS.com hari ini dan lepaskan potensi perdagangan indeks saham.',
    'STOCK_INDICES_TRADING' => 'PERDAGANGAN INDEKS SAHAM DENGAN XS',
    'DESCRIPTION_2' => 'XS menawarkan kesempatan untuk berdagang CFD pada indeks spot, memberikan trader waktu perdagangan yang lebih panjang dan fleksibilitas untuk membuka posisi long dan short. Dengan terlibat dalam perdagangan indeks, trader dapat mendiversifikasi portofolio mereka dan mengurangi risiko dengan berinvestasi dalam sekeranjang aset, daripada bergantung pada beberapa investasi individual.',
    'UNDERSTANDING_INDICES_TRADING' => 'Memahami Perdagangan Indeks: Sebuah Ikhtisar bersama XS',
    'UNDERSTANDING_INDICES_DESC_1' => 'Indeks berfungsi sebagai indikator harga untuk sekelompok sekuritas, mewakili "keranjang" saham dengan dasar yang sama. Perdagangan indeks memungkinkan Anda membuka posisi tentang kinerja beberapa saham secara bersamaan.',
    'UNDERSTANDING_INDICES_DESC_2' => 'Hal-hal penting yang perlu diperhatikan tentang indeks: Komposisi: Setiap indeks terbentuk dari kumpulan saham atau obligasi tertentu. Inklusi saham-saham ini dalam perhitungan indeks memberikan informasi berharga tentang dinamikanya. Indikator Investor: Indeks dunia berfungsi sebagai indikator kuat bagi investor, menawarkan wawasan tentang arah kutipan dalam industri tertentu. Mempelajari indeks utama membantu memahami bagaimana beberapa peristiwa memengaruhi nilai sekuritas.',
    'UNDERSTANDING_INDICES_DESC_3' => 'Reaksi Tak Terduga: Penting untuk diingat bahwa reaksi pasar terhadap berita ekonomi tidak selalu sesuai dengan harapan dan perkiraan. Sebagai contoh, ketika harga minyak naik, secara logis kita dapat mengharapkan kenaikan saham-saham perusahaan minyak. Namun, saham-saham individual dapat tumbuh dengan kecepatan yang berbeda atau tidak merespons sama sekali. Dalam kasus seperti itu, indeks spot membantu trader memahami tren pasar secara keseluruhan dalam segmen tersebut tanpa menilai posisi setiap perusahaan.',
    'UNDERSTANDING_INDICES_DESC_4' => 'Melihat dan berdagang indeks memberikan wawasan tentang perbandingan sektor dalam ekonomi. XS menawarkan syarat-syarat perdagangan yang komprehensif, kutipan yang akurat dari beberapa penyedia, dan analisis yang serbaguna untuk perdagangan indeks.',
];
?>
