<?php
return [
    'SHARES_DESCRIPTION' => 'XS Group adalah penyedia layanan keuangan dan teknologi finansial global dengan entitas yang diatur dan diotorisasi oleh lembaga pemerintahan terkemuka di yurisdiksi keuangan yang paling terkemuka di seluruh dunia. Kami mengutamakan kepatuhan regulasi untuk memastikan kepercayaan, integritas, dan akuntabilitas dalam industri keuangan global. Operasi kami mematuhi regulasi dan persyaratan yang ditetapkan oleh otoritas yang relevan di setiap yurisdiksi tempat kami beroperasi.',
    'INVEST_IN_POPULAR_COMPANIES_WITH_A_GLOBAL_BROKER' => 'INVESTASI DI PERUSAHAAN POPULER BERSAMA BROKER GLOBAL',
    'DESCRIPTION_1' => 'Buka akses ke Perusahaan Paling Populer di Dunia dan Perdagangkan CFD Saham Internasional dengan XS. Dapatkan Akses ke Pasar Global dan Bertransaksi dengan Mudah Membeli dan Menjual Perusahaan Terkemuka seperti Amazon, Alibaba, Apple, dan lainnya. Bergabunglah dengan XS.com hari ini dan buka potensi perdagangan Saham & Saham di pasar global.',
    'SHARES_STOCKS_TRADING_WITH_XS' => 'PERDAGANGAN SAHAM DENGAN XS',
    'DESCRIPTION_2' => 'Rasakan sensasi perdagangan Saham dengan XS.com. Manfaatkan kemampuan perdagangan CFD yang mulus dari platform kami, yang menawarkan Anda kesempatan untuk bertransaksi CFD pada ribuan saham global. Manfaatkan eksekusi order yang sangat cepat dan kondisi perdagangan yang kompetitif, memastikan Anda dapat memanfaatkan peluang pasar dengan cepat dan efisien. Berdagang CFD pada saham-saham perusahaan terkenal di AS, Inggris, dan Uni Eropa, termasuk beberapa perusahaan terbesar dan paling populer.',
    'UNDERSTANDING_SHARES' => 'Memahami Saham: Sebuah Tinjauan',
    'UNDERSTANDING_SHARES_DESC_1' => 'Saham adalah jenis sekuritas yang memberikan investor kepemilikan sebagian pada sebuah perusahaan, beserta dengan hak dan manfaat tertentu. Berikut yang perlu Anda ketahui tentang saham:',
    'UNDERSTANDING_SHARES_DESC_2' => 'Dua Jenis Utama Saham Saham Biasa: Sekuritas ini memberikan pemiliknya hak suara dan kesempatan untuk berpartisipasi dalam distribusi dividen. Rapat umum pemegang saham, di mana keputusan dibuat melalui pemungutan suara, adalah lembaga pemerintahan tertinggi perusahaan. Biasanya, setiap saham membawa satu suara, yang berarti pemegang saham dengan kepemilikan lebih besar memiliki lebih banyak pengaruh dalam pengambilan keputusan.',
    'UNDERSTANDING_SHARES_DESC_3' => 'Saham Preferen: Jenis saham ini menawarkan keuntungan dalam distribusi dividen dan prioritas dalam kasus kebangkrutan. Pemegang saham preferen menerima dividen sebelum pemegang saham biasa dan memiliki klaim yang lebih tinggi terhadap aset perusahaan selama likuidasi. Namun, pemilik saham preferen umumnya tidak memiliki hak suara dalam rapat pemegang saham.',
    'UNDERSTANDING_SHARES_DESC_4' => 'Alasan Perusahaan Menerbitkan Saham Pencapaian Modal: Perusahaan menerbitkan saham sebagai sarana untuk mengumpulkan modal. Dana yang dihasilkan dari penjualan saham dapat digunakan untuk mendukung pertumbuhan bisnis, seperti perluasan operasi, investasi dalam penelitian dan pengembangan, atau peningkatan modal kerja.',
    'UNDERSTANDING_SHARES_DESC_5' => 'Reputasi dan Citra: Penerbitan saham menambah reputasi perusahaan dan meningkatkan citra korporatnya. Ini meningkatkan visibilitas, transparansi, dan daya tarik perusahaan bagi investor potensial yang ingin berpartisipasi dalam aktivitas perdagangan. Untuk terdaftar di bursa saham untuk perdagangan, saham perusahaan harus melewati proses penilaian.',
    'UNDERSTANDING_SHARES_DESC_6' => 'Saham memainkan peran penting dalam lanskap korporat, memungkinkan investor menjadi pemilik sebagian dan menikmati manfaat berdasarkan kinerja perusahaan. Baik saham biasa maupun saham preferen menawarkan peluang partisipasi, dividen, dan potensi apresiasi modal. Sebagai investor, memahami berbagai jenis saham dan implikasinya dapat membantu Anda dalam membuat keputusan investasi.',
];
?>
