<?php
return [
    'SHARES_DESCRIPTION' => 'XS Group è un fornitore globale di servizi finanziari e tecnologici con entità regolamentate e autorizzate dalle principali autorità di controllo delle giurisdizioni finanziarie più rinomate in tutto il mondo. Diamo priorità alla conformità normativa per garantire fiducia, integrità e responsabilità nell\'industria finanziaria globale. Le nostre operazioni sono conformi alle normative e ai requisiti stabiliti dalle autorità competenti in ciascuna giurisdizione in cui operiamo.',
    'INVEST_IN_POPULAR_COMPANIES_WITH_A_GLOBAL_BROKER' => 'INVESTI IN AZIENDE POPOLARI CON UN BROKER GLOBALE',
    'DESCRIPTION_1' => 'Sblocca le azioni delle aziende più popolari al mondo e fai trading di CFD su azioni internazionali con XS. Accedi ai mercati globali e acquista e vendi facilmente le azioni delle principali aziende come Amazon, Alibaba, Apple e altre ancora. Unisciti a XS.com oggi stesso e scopri il potenziale del trading di azioni nei mercati globali.',
    'SHARES_STOCKS_TRADING_WITH_XS' => 'TRADING DI AZIONI CON XS',
    'DESCRIPTION_2' => 'Vivi l\'emozione del trading di azioni con XS.com. Approfitta delle capacità di trading di CFD senza soluzione di continuità delle nostre piattaforme, che ti offrono l\'opportunità di fare trading di CFD su migliaia di azioni globali. Beneficia di esecuzioni degli ordini ultra veloci e condizioni di trading competitive, garantendo che tu possa cogliere rapidamente ed efficacemente le opportunità di mercato. Fai trading di CFD su azioni di aziende famose negli Stati Uniti, nel Regno Unito e nell\'Unione Europea, tra cui alcune delle più grandi e popolari società.',
    'UNDERSTANDING_SHARES' => 'Comprensione delle Azioni: Una Panoramica',
    'UNDERSTANDING_SHARES_DESC_1' => 'Le azioni sono un tipo di titolo che conferisce agli investitori la proprietà parziale di un\'azienda, insieme a determinati diritti e benefici. Ecco cosa devi sapere sulle azioni:',
    'UNDERSTANDING_SHARES_DESC_2' => 'Due Principali Tipi di Azioni Azioni Ordinarie: Questi titoli forniscono ai proprietari il diritto di voto e l\'opportunità di partecipare alla distribuzione dei dividendi. L\'assemblea generale dei soci, dove le decisioni vengono prese attraverso il voto, è l\'organo direttivo più elevato dell\'azienda. Generalmente, ogni azione comporta un voto, il che significa che i grandi azionisti hanno maggiore influenza sulle decisioni.',
    'UNDERSTANDING_SHARES_DESC_3' => 'Azioni Privilegiate: Questo tipo di azione offre vantaggi in termini di distribuzione dei dividendi e priorità in caso di fallimento. I detentori di azioni privilegiate ricevono dividendi prima dei detentori di azioni ordinarie e hanno un diritto di prelazione più elevato sugli asset dell\'azienda durante la liquidazione. Tuttavia, i proprietari di azioni privilegiate di solito non hanno diritto di voto nelle assemblee dei soci.',
    'UNDERSTANDING_SHARES_DESC_4' => 'Motivi per cui le Aziende Emettono Azioni Raccolta di Capitale: Le aziende emettono azioni come mezzo per raccogliere capitale. I fondi generati dalla vendita delle azioni possono essere utilizzati per sostenere la crescita aziendal\'espansione delle operazioni, gli investimenti nella ricerca e sviluppo o il potenziamento del capitale circolante.',
    'UNDERSTANDING_SHARES_DESC_5' => 'Reputazione e Immagine: L\'emissione di azioni contribuisce alla reputazione di un\'azienda e ne migliora l\'immagine aziendale. Aumenta la visibilità, la trasparenza e l\'attrattiva dell\'azienda per gli investitori potenziali che desiderano partecipare alle attività di trading. Per essere quotata in borsa per il trading, le azioni di un\'azienda devono prima superare il processo di quotazione.',
    'UNDERSTANDING_SHARES_DESC_6' => 'Le azioni svolgono un ruolo vitale nel panorama aziendale, consentendo agli investitori di diventare proprietari parziali e godere dei benefici basati sulle performance dell\'azienda. Che siano azioni ordinarie o privilegiate, offrono opportunità di partecipazione, dividendi e potenziale apprezzamento del capitale. Come investitore, comprendere i diversi tipi di azioni e le loro implicazioni può aiutarti nelle decisioni di investimento.',
];
?>
