<?php
return [
    'INDICES_DESCRIPTION' => 'Die XS Group ist ein globaler Finanztechnologie- und Finanzdienstleister mit von führenden Aufsichtsbehörden in den renommiertesten Finanzjurisdiktionen weltweit regulierten und autorisierten Einheiten. Wir legen großen Wert auf die Einhaltung der Regulierung, um Vertrauen, Integrität und Rechenschaftspflicht in der globalen Finanzbranche sicherzustellen. Unsere Aktivitäten entsprechen den Vorschriften und Anforderungen der jeweiligen Behörden in den Rechtsgebieten, in denen wir tätig sind.',
    'TRADE_WORKDS_LEADING' => 'HANDELN SIE MIT DEN WELTWEIT FÜHRENDEN AKTIENINDIZES BEI EINEM GLOBAL AGIERENDEN BROKER',
    'DESCRIPTION_1' => 'Nutzen Sie die Möglichkeiten des Handels mit den weltweit führenden Aktienindizes und handeln Sie internationale Aktienindizes mit XS. Erhalten Sie Zugang zu den globalen Märkten und kaufen und verkaufen Sie nahtlos führende Aktienindizes wie den Dow Jones, den DAX, die Nasdaq und mehr. Treten Sie noch heute XS.com bei und entfesseln Sie die Kraft des Aktienindexhandels.',
    'STOCK_INDICES_TRADING' => 'AKTIENINDEX-HANDEL MIT XS',
    'DESCRIPTION_2' => 'XS bietet die Möglichkeit, CFDs auf Spotindizes zu handeln, was den Händlern erweiterte Handelszeiten und die Flexibilität bietet, sowohl Long- als auch Short-Positionen einzugehen. Durch die Teilnahme am Indexhandel können Händler ihre Portfolios diversifizieren und Risiken durch Investitionen in einen breiten Korb von Vermögenswerten mindern, anstatt sich auf wenige Einzelinvestitionen zu verlassen.',
    'UNDERSTANDING_INDICES_TRADING' => 'Verständnis des Indexhandels: Ein Überblick mit XS',
    'UNDERSTANDING_INDICES_DESC_1' => 'Indizes dienen als Preisindikatoren für eine Gruppe von Wertpapieren und repräsentieren einen "Korb" von Aktien mit einer gemeinsamen Basis. Der Handel mit Indizes ermöglicht es Ihnen, Positionen zur Wertentwicklung mehrerer Aktien gleichzeitig zu eröffnen.',
    'UNDERSTANDING_INDICES_DESC_2' => 'Wichtige Punkte zum Thema Indizes: Zusammensetzung: Jeder Index setzt sich aus einer bestimmten Gruppe von Aktien oder Anleihen zusammen. Die Aufnahme dieser Aktien in die Indexberechnung liefert wertvolle Informationen über deren Dynamik. Anlegerindikator: Weltweite Indizes fungieren als leistungsstarke Indikatoren für Anleger und bieten Einblicke in die Richtung von Angeboten in bestimmten Branchen. Die Untersuchung wichtiger Indizes hilft zu verstehen, wie bestimmte Ereignisse den Wert von Wertpapieren beeinflussen.',
    'UNDERSTANDING_INDICES_DESC_3' => 'Unvorhergesehene Reaktionen: Es ist wichtig zu beachten, dass die Marktreaktion auf wirtschaftliche Nachrichten nicht immer mit Erwartungen und Prognosen in Einklang stehen muss. Wenn beispielsweise die Ölpreise steigen, ist es logisch, eine Zunahme der Aktienkurse von Ölunternehmen zu erwarten. Die einzelnen Aktien können jedoch unterschiedlich schnell wachsen oder überhaupt nicht reagieren. In solchen Fällen helfen Spotindizes den Händlern, den allgemeinen Markttrend in diesem Segment zu verstehen, ohne die Position jedes Unternehmens bewerten zu müssen.',
    'UNDERSTANDING_INDICES_DESC_4' => 'Die Beobachtung und der Handel mit Indizes bieten Einblicke in den Vergleich von Branchen innerhalb der Wirtschaft. XS bietet umfassende Handelsbedingungen, genaue Kurse von mehreren Anbietern und vielseitige Analysen für den Handel mit Indizes.',
];
?>
