<?php
return [
    'SHARES_DESCRIPTION' => 'Die XS Group ist ein globaler Fintech- und Finanzdienstleister mit Einheiten, die von führenden Aufsichtsbehörden der renommiertesten Finanzjurisdiktionen auf der ganzen Welt reguliert und autorisiert sind. Wir legen großen Wert auf die Einhaltung regulatorischer Vorschriften, um Vertrauen, Integrität und Rechenschaftspflicht in der globalen Finanzbranche sicherzustellen. Unsere Operationen entsprechen den Vorschriften und Anforderungen, die von den jeweiligen Behörden in jeder Gerichtsbarkeit festgelegt wurden, in der wir tätig sind.',
    'INVEST_IN_POPULAR_COMPANIES_WITH_A_GLOBAL_BROKER' => 'INVESTIEREN SIE IN BELIEBTE UNTERNEHMEN BEI EINEM WELTWEITEN BROKER',
    'DESCRIPTION_1' => 'Schalten Sie die weltweit beliebtesten Unternehmen frei und handeln Sie internationale Aktien-CFDs mit XS. Erhalten Sie Zugang zu globalen Märkten und kaufen und verkaufen Sie nahtlos führende Unternehmen wie Amazon, Alibaba, Apple und mehr. Treten Sie noch heute XS.com bei und entdecken Sie das Potenzial des Aktien- und Aktienhandels in den globalen Märkten.',
    'SHARES_STOCKS_TRADING_WITH_XS' => 'AKTIENHANDEL MIT XS',
    'DESCRIPTION_2' => 'Erleben Sie die Spannung des Aktien- und Aktienhandels mit XS.com. Nutzen Sie die nahtlosen CFD-Handelsmöglichkeiten unserer Plattformen, die Ihnen die Möglichkeit bieten, CFDs auf Tausende von globalen Aktien zu handeln. Profitieren Sie von ultraschneller Auftragsausführung und wettbewerbsfähigen Handelsbedingungen, um Marktmöglichkeiten schnell und effizient nutzen zu können. Handeln Sie CFDs auf Aktien namhafter Unternehmen in den USA, Großbritannien und der EU, darunter einige der größten und bekanntesten Konzerne.',
    'UNDERSTANDING_SHARES' => 'Verständnis von Aktien: Ein Überblick',
    'UNDERSTANDING_SHARES_DESC_1' => 'Aktien sind eine Art von Wertpapier, das Investoren eine teilweise Eigentümerschaft an einem Unternehmen sowie bestimmte Rechte und Vorteile gewährt. Hier erfahren Sie, was Sie über Aktien wissen müssen:',
    'UNDERSTANDING_SHARES_DESC_2' => 'Zwei Hauptarten von Aktien Stammaktien: Diese Wertpapiere verleihen den Eigentümern Stimmrechte und die Möglichkeit zur Teilnahme an der Ausschüttung von Dividenden. Die Hauptversammlung der Aktionäre, bei der Entscheidungen durch Abstimmung getroffen werden, ist das höchste Entscheidungsgremium des Unternehmens. Jede Aktie trägt in der Regel eine Stimme, was bedeutet, dass größere Aktionäre mehr Einfluss auf die Entscheidungsfindung haben.',
    'UNDERSTANDING_SHARES_DESC_3' => 'Vorzugsaktien: Diese Art von Aktien bietet Vorteile bei der Ausschüttung von Dividenden und Vorrang im Falle einer Insolvenz. Vorzugsaktionäre erhalten Dividenden vor den Stammaktionären und haben einen höheren Anspruch auf Unternehmensvermögen bei Liquidation. In der Regel haben Inhaber von Vorzugsaktien jedoch keine Stimmrechte auf Aktionärstreffen.',
    'UNDERSTANDING_SHARES_DESC_4' => 'Gründe für Unternehmen, Aktien auszugeben Kapitalbeschaffung: Unternehmen geben Aktien aus, um Kapital zu beschaffen. Die aus dem Verkauf von Aktien erzielten Mittel können zur Finanzierung des Unternehmenswachstums verwendet werden, wie etwa zur Expansion der Geschäftstätigkeit, zur Investition in Forschung und Entwicklung oder zur Stärkung des Betriebskapitals.',
    'UNDERSTANDING_SHARES_DESC_5' => 'Ruf und Image: Die Ausgabe von Aktien trägt zum Ruf eines Unternehmens bei und verbessert sein Unternehmensimage. Es erhöht die Sichtbarkeit, Transparenz und Attraktivität des Unternehmens für potenzielle Investoren, die an Handelsaktivitäten teilnehmen möchten. Um an einer Börse zum Handel zugelassen zu werden, muss die Aktie des Unternehmens zuerst den Zulassungsprozess durchlaufen.',
    'UNDERSTANDING_SHARES_DESC_6' => 'Aktien spielen eine wichtige Rolle in der Unternehmenswelt und ermöglichen es Investoren, teilweise Eigentümer zu werden und von den Leistungen des Unternehmens zu profitieren. Ob Stamm- oder Vorzugsaktien, Aktien bieten Möglichkeiten zur Beteiligung, zur Ausschüttung von Dividenden und zur potenziellen Wertsteigerung des Kapitals. Als Investor kann das Verständnis der verschiedenen Aktienarten und ihrer Auswirkungen Ihnen bei Ihren Anlageentscheidungen helfen.',
];
?>
